
-- QUERY ROL ADD
INSERT INTO `rol` VALUES (1, 'admin', 'Administrador');
INSERT INTO `rol` VALUES (2, 'colab', 'Colaborador');

-- QUERY AREA ADD
INSERT INTO `area` VALUES (1,'Developers');
INSERT INTO `area` VALUES (2,'Director General');
INSERT INTO `area` VALUES (3,'Administrativa');
INSERT INTO `area` VALUES (4,'Académica');
INSERT INTO `area` VALUES (5,'Investigación');
INSERT INTO `area` VALUES (6,'Contabilidad');
INSERT INTO `area` VALUES (7,'Construcción');
INSERT INTO `area` VALUES (8,'Admisión');
INSERT INTO `area` VALUES (9,'Secretaría Académica');
INSERT INTO `area` VALUES (10,'Comunicación');
INSERT INTO `area` VALUES (11,'Sistemas');
INSERT INTO `area` VALUES (12,'Calidad Educativa');
INSERT INTO `area` VALUES (13,'Experiencia del Estudiante');
INSERT INTO `area` VALUES (14,'Recaudaciones');
INSERT INTO `area` VALUES (15,'Educación Continua');
INSERT INTO `area` VALUES (16,'Tesorería');
INSERT INTO `area` VALUES (17,'RATEC');
INSERT INTO `area` VALUES (18,'Centro de Idiomas');
INSERT INTO `area` VALUES (19,'Centro de Información');
INSERT INTO `area` VALUES (20,'Bienestar');
INSERT INTO `area` VALUES (21,'Talento Humano');
INSERT INTO `area` VALUES (22,'Legal');
INSERT INTO `area` VALUES (23,'Mantenimiento, Seguridad y Limpieza');

-- QUERY USER ADD
INSERT INTO `usuario` VALUES (1,'admin','admin',1);
INSERT INTO `usuario` VALUES (2,'joaocisneros@elp.edu.pe','Pontificia2023',2);
INSERT INTO `usuario` VALUES (3,'dianacurilla@elp.edu.pe','Pontificia2023',2);
INSERT INTO `usuario` VALUES (4,'henrysalcedo@elp.edu.pe','Pontificia2023',2);
INSERT INTO `usuario` VALUES (5, 'julioflores@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (6, 'adamedina@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (7, 'albertogutierrez@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (8, 'anacristhinahuaman@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (9, 'anamariacabrera@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (10, 'anayelyromero@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (11, 'andreamorote@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (12, 'andresoblitas@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (13, 'angeladiaz@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (14, 'angelaquispe@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (15, 'anitineo@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (16, 'asistentelegal@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (17, 'Aylingonzales@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (18, 'bettydelacruz@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (19, 'bezaibellido@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (20, 'carlosataurima@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (21, 'carlosayala@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (22, 'carmenlainez@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (23, 'carolinaperalta@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (24, 'catyccasani@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (25, 'cecilialeandro@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (26, 'cesargutierrez@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (27, 'christianreymundez@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (28, 'contabilidad@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (29, 'cristinaleche@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (31, 'davidataupillco@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (32, 'deysisalinas@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (33, 'edgararones@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (34, 'elizabethmoises@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (35, 'elsasosa@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (36, 'elvisconga@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (37, 'erikamonteras@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (38, 'estefanychuchon@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (39, 'evelyngutierrez@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (40, 'felicianoapaico@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (41, 'florvilcapoma@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (42, 'francoayala@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (43, 'franzasto@ilp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (44, 'Freyberguillen@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (45, 'gianellasaldana@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (46, 'gloriaclavo@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (47, 'guiselagutierrez@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (48, 'ivettenicolas@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (49, 'jackelinemedina@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (50, 'jamesquispe@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (51, 'jammesbaladilla@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (52, 'janmcuri@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (53, 'jasonflores@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (54, 'jersondelacruz@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (55, 'jhonymartinez@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (56, 'josegaray@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (57, 'joseluisvargas@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (58, 'josemartinez@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (59, 'juanmendez@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (60, 'juanmendoza@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (61, 'juliaochatoma@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (62, 'karinafarfan@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (63, 'katherinacosta@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (64, 'katihuscamedina@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (65, 'kendychavez@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (66, 'keylagalvez@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (67, 'leydivalera@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (68, 'lidiacasas@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (69, 'liduvinacangana@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (70, 'lizbarrientos@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (71, 'lizieguillen@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (72, 'lizjaulis@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (73, 'luisbaldeon@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (74, 'luisgeraldo@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (75, 'luzgutierrez@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (76, 'mabilonhuaman@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (77, 'manuelapaza@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (78, 'manuelgongora@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (79, 'margaritagutierrez@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (80, 'mariaesther@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (81, 'maryalfaro@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (82, 'maximilianolapa@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (83, 'melanienarvaez@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (84, 'melanihuamani@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (85, 'melaniyaranga@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (86, 'melinalaura@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (87, 'moisesquispe@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (88, 'natalyorihuela@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (89, 'neysiauqui@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (90, 'nicolruiz@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (91, 'nikoskanicolas@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (92, 'nilgarcia@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (93, 'niltonsulca@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (94, 'NoevalinaBorda@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (95, 'noragonzales@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (96, 'raquelochante@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (97, 'reyshellramos@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (98, 'ricardotaco@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (99, 'richardmayta@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (100, 'rosatorres@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (101, 'rossyloayza@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (102, 'rossyyulgo@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (103, 'ruthcardenas@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (104, 'ruthore@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (105, 'ruthperez@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (106, 'ruthvalladolid@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (107, 'rutmanquispe@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (108, 'sandrahuarcaya@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (109, 'saraserna@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (110, 'sayuriespino@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (111, 'sintiatenorio@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (113, 'sthefanovega@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (114, 'suselbarrientos@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (115, 'thaliabermudo@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (116, 'thaliahuaman@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (117, 'urpifalco@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (118, 'vanesallampasi@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (119, 'vickihuaman@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (120, 'victorayala@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (121, 'wilmeranccasi@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (122, 'yansinegamboa@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (124, 'yennifercalle@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (125, 'yesicameza@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (126, 'yoanacardenas@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (127, 'yolimarmeses@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (128, 'yoninicolas@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (129, 'yulyechaccaya@elp.edu.pe', 'Pontificia2023', 2);
INSERT INTO `usuario` VALUES (130, 'yulyfernandez@elp.edu.pe', 'Pontificia2023', 2);


-- QUERY DEPARTAMENT ADD
INSERT INTO `departamento` VALUES (1,'Developers');
INSERT INTO `departamento` VALUES (2,'General');
INSERT INTO `departamento` VALUES (3,'Administrativa');
INSERT INTO `departamento` VALUES (4,'Academico');
INSERT INTO `departamento` VALUES (5,'Investigacion e Innovacion');
INSERT INTO `departamento` VALUES (6,'Marketing y Comercial');
INSERT INTO `departamento` VALUES (7,'Secretaria Academica');
INSERT INTO `departamento` VALUES (8,'Educacion Continua');
INSERT INTO `departamento` VALUES (9,'Centro de Idiomas');

-- QUERY POST ADD
INSERT INTO `puesto` VALUES (1, 'Developers');
INSERT INTO `puesto` VALUES (2, 'Director');
INSERT INTO `puesto` VALUES (3, 'Asesor');
INSERT INTO `puesto` VALUES (4, 'Jefe');
INSERT INTO `puesto` VALUES (5, 'Coordinador');
INSERT INTO `puesto` VALUES (6, 'Analista');
INSERT INTO `puesto` VALUES (7, 'Asistente');
INSERT INTO `puesto` VALUES (8, 'Practicante');
INSERT INTO `puesto` VALUES (9, 'Operario');

-- QUERY SEDE ADD
INSERT INTO `sede` VALUES (1,'Developers');
INSERT INTO `sede` VALUES (2,'Alameda');
INSERT INTO `sede` VALUES (3,'Jazmines');
INSERT INTO `sede` VALUES (4,'Casuarinas');
INSERT INTO `sede` VALUES (5,'Colegio');

-- QUERY CARGO ADD
INSERT INTO `cargo` VALUES (1,'Developers');
INSERT INTO `cargo` VALUES (2,'Director general');
INSERT INTO `cargo` VALUES (3,'Directora adjunta');
INSERT INTO `cargo` VALUES (4,'Director administrativo');
INSERT INTO `cargo` VALUES (5,'Director academico');
INSERT INTO `cargo` VALUES (6,'Director de investigacion e innovacion');
INSERT INTO `cargo` VALUES (7,'Asesor legal');
INSERT INTO `cargo` VALUES (8,'Asesor de contabilidad y tributacion');
INSERT INTO `cargo` VALUES (9,'Asesor de gestion estrategica');
INSERT INTO `cargo` VALUES (10,'Jefe de Infraestructura');
INSERT INTO `cargo` VALUES (11,'Jefe de Admision ELP');
INSERT INTO `cargo` VALUES (12,'Jefe Secretaria Academica ILP y ELP');
INSERT INTO `cargo` VALUES (13,'Jefe de Registro de Grados y Titulos');
INSERT INTO `cargo` VALUES (14,'Jefe Academico C. Salud');
INSERT INTO `cargo` VALUES (15,'Jefe de Comunicaciones');
INSERT INTO `cargo` VALUES (16,'Jefe de Sistemas');
INSERT INTO `cargo` VALUES (17,'Jefe Academico C. Gestion y Tecnologia');
INSERT INTO `cargo` VALUES (18,'Jefe de Admision ILP');
INSERT INTO `cargo` VALUES (19,'Jefe gestion personas');
INSERT INTO `cargo` VALUES (20,'Coordinador Academico C. Salud');
INSERT INTO `cargo` VALUES (21,'Coordinador Certificaciones');
INSERT INTO `cargo` VALUES (22,'Coordinadora de Experiencia del Estudiante');
INSERT INTO `cargo` VALUES (23,'Coordinadora Secretaria Academica ILP ');
INSERT INTO `cargo` VALUES (24,'Coordinador de Comunicacion ILP');
INSERT INTO `cargo` VALUES (25,'Coordinador de Contabilidad');
INSERT INTO `cargo` VALUES (26,'Coordinador de Recaudacion');
INSERT INTO `cargo` VALUES (27,'Coordinador de Calidad Educativa');
INSERT INTO `cargo` VALUES (28,'Coordinador de Educacion Continua');
INSERT INTO `cargo` VALUES (29,'Coordinadora de Tesoreria');
INSERT INTO `cargo` VALUES (30,'Coordinador de Academico C. Gestion y TI');
INSERT INTO `cargo` VALUES (31,'Coordinador de Servicios y Demanda');
INSERT INTO `cargo` VALUES (32,'Coordinador de Comunicaciones: Cybernet, RRPP y Prensa');
INSERT INTO `cargo` VALUES (33,'Jefe de Gestion de Personas');
INSERT INTO `cargo` VALUES (34,'Coordinador de Comunicaciones ELP');
INSERT INTO `cargo` VALUES (35,'Coordinador de cloud, redes y conectividad');
INSERT INTO `cargo` VALUES (36,'Coordinador de Comunicaciones: Educacion Continua y Centro de Idiomas');
INSERT INTO `cargo` VALUES (37,'Coordinador de RATEC');
INSERT INTO `cargo` VALUES (38,'Coordinador del Centro de Idiomas');
INSERT INTO `cargo` VALUES (39,'Coordinador del Centro de Información');
INSERT INTO `cargo` VALUES (40,'Coordinado de Bienestar');
INSERT INTO `cargo` VALUES (41,'Coordinador de Talento');
INSERT INTO `cargo` VALUES (42,'Analista de Contabilidad');
INSERT INTO `cargo` VALUES (43,'Analista de Secretaria Academica del ILP');
INSERT INTO `cargo` VALUES (44,'Analista Legal');
INSERT INTO `cargo` VALUES (45,'Analista de mesa de ayuda');
INSERT INTO `cargo` VALUES (46,'Analista de Calidad Educativa');
INSERT INTO `cargo` VALUES (47,'Analista de Diseño y Producción ILP');
INSERT INTO `cargo` VALUES (48,'Analista de Experiencia del Estudiante');
INSERT INTO `cargo` VALUES (49,'Asistente de Direccion General');
INSERT INTO `cargo` VALUES (50,'Asistente de Comunicaciones: Educacion Continua y Centro de Idiomas');
INSERT INTO `cargo` VALUES (51,'Asistente de Tesoreia');
INSERT INTO `cargo` VALUES (52,'Asesor  de Admision ILP');
INSERT INTO `cargo` VALUES (53,'Asesor de Admision idiomas');
INSERT INTO `cargo` VALUES (54,'Asistente Modulos');
INSERT INTO `cargo` VALUES (55,'Asistente Secretaria Academica ILP');
INSERT INTO `cargo` VALUES (56,'Asistente de Certificaciones');
INSERT INTO `cargo` VALUES (57,'Asistente Administrativo');
INSERT INTO `cargo` VALUES (58,'Asistente de Infraestructura');
INSERT INTO `cargo` VALUES (59,'Asesor  de Admision ILP Y ELP');
INSERT INTO `cargo` VALUES (60,'Asistente de Bienestar');
INSERT INTO `cargo` VALUES (61,'Asistente Academico C. Gestion y Tecnologia ');
INSERT INTO `cargo` VALUES (62,'Asistente Secretaria Academica ELP');
INSERT INTO `cargo` VALUES (63,'Asistente de Redes Sociales');
INSERT INTO `cargo` VALUES (64,'Asistente de Sistemas');
INSERT INTO `cargo` VALUES (65,'Asistente de Seguridad y Camaras');
INSERT INTO `cargo` VALUES (66,'Asistente de Experiencia del Estudiante');
INSERT INTO `cargo` VALUES (67,'Asistente de Topico ');
INSERT INTO `cargo` VALUES (68,'Asistente de Registro de Grados y Titulos');
INSERT INTO `cargo` VALUES (69,'Asistente de Contabilidad');
INSERT INTO `cargo` VALUES (70,'Asistente de Calidad Educativa');
INSERT INTO `cargo` VALUES (71,'Asistente Academico C. Salud');
INSERT INTO `cargo` VALUES (72,'Asesor de Admision ELP');
INSERT INTO `cargo` VALUES (73,'Asesor de Admision Continua');
INSERT INTO `cargo` VALUES (74,'Asistente de Recaudacion');
INSERT INTO `cargo` VALUES (75,'Practicante de Certificaciones');
INSERT INTO `cargo` VALUES (76,'Practicante de mesa de ayuda');
INSERT INTO `cargo` VALUES (77,'Practicante Secretaria Academica ILP');
INSERT INTO `cargo` VALUES (78,'Practicante de Comunicaciones');
INSERT INTO `cargo` VALUES (79,'Practicante de Experiencia del Estudiante');
INSERT INTO `cargo` VALUES (80,'Mentor');
INSERT INTO `cargo` VALUES (81,'Operario de Logistica');
INSERT INTO `cargo` VALUES (82,'Operario de Seguridad');
INSERT INTO `cargo` VALUES (83,'Operario de Limpieza');

-- QUERY COLABORDAROR ADD
INSERT INTO `colaborador` VALUES (1,'99999999','Usuario','admin',1,1,1,1,1,1,1);